CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR NOT NULL,
	password VARCHAR NOT NULL,
	email VARCHAR NOT NULL
);

CREATE TABLE books (
	id SERIAL PRIMARY KEY,
	title VARCHAR NOT NULL,
	author VARCHAR NOT NULL,
	year INTEGER NOT NULL,
	isbn VARCHAR NOT NULL
);

CREATE TABLE reviews (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users,
	book_id INTEGER REFERENCES books,
	rating INTEGER NOT NULL,
	text VARCHAR NOT NULL
);
